### ISSUE TITLE
Please post an example of using CDK with ElasticSearch  with python

### ISSUE THREAD

**Issue by si3mshady** [aws-samples/aws-cdk-examples#304]
I really needed an example of how to set up ElasticSearch with CDK, I dont want to use other IAC tools, unfortunately there is none.
I tried setting it up on my own with what I hoped was a bare bones deployment of an ES cluster however, there is not sufficient guidance to help with that. Can someone please just post an example 

/3 | 5:25:52 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata         | CDKMetadata 
 0/3 | 5:25:52 PM | CREATE_IN_PROGRESS   | AWS::Elasticsearch::Domain | es-vpc-ling (esvpcling) 
 1/3 | 5:25:52 PM | CREATE_FAILED        | AWS::Elasticsearch::Domain | es-vpc-ling (esvpcling) EBS storage must be selected for m4.large.elasticsearch (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 10b2eee2-4b62-466f-be48-3d36be64484b)

**Comment by orozcoadrian** [comment]
I'm currently working on deploying ElasticSearch with cloudformation. I'm not done yet but I was able to get an initial deployment following this: https://aws.amazon.com/blogs/field-notes/launch-amazon-elasticsearch-service-with-amazon-cognito-user-pools/ (I generated the template using the cdk but deployed it manually via the cloudformation console)

I ran into that same EBS error. [This](https://aws.amazon.com/elasticsearch-service/pricing/) page  helped me understand that I had to enable EBS in my template.

Here's the template that finally worked for me:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ED4WTPS:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
        DomainName: one
        EBSOptions:
            EBSEnabled: true
            VolumeSize: 10
        ElasticsearchClusterConfig:
            InstanceType: t2.small.elasticsearch
        ElasticsearchVersion: '7.1'
```
Hope that helps.
